# Generated by Django 5.2.5 on 2025-08-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0002_dynamictabledefinition_dynamictableexport'),
        ('data_generator', '0003_create_sell'),
        ('data_generator', '0004_create_sells'),
        ('data_generator', '0005_create_sells1'),
        ('data_generator', '0006_create_buy_things'),
    ]

    operations = [
    ]
