# Generated by Django 5.2.5 on 2025-08-26 02:50
# Cleanup migration to remove old JSON schema tables

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0008_create_sell_cars'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS data_generator_syntheticdatarecord;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS data_generator_datageneration;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS data_generator_dataschema;",
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]
