# Generated by Django 5.2.5 on 2025-10-07 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0011_create_venta_autos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(default='initializing', max_length=50)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='data_generator.dynamictableexport')),
            ],
        ),
    ]
